<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="277" started-at="2021-10-03T22:56:23 COT" finished-at="2021-10-03T22:56:24 COT">
    <groups>
    </groups>
    <test name="Casos de Prueba Carrito de Compras" duration-ms="277" started-at="2021-10-03T22:56:23 COT" finished-at="2021-10-03T22:56:24 COT">
      <class name="testcases.CasosCarrito">
        <test-method status="PASS" signature="AbrirNavegador(org.testng.ITestContext)[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="AbrirNavegador" is-config="true" duration-ms="467" started-at="2021-10-03T22:56:23 COT" finished-at="2021-10-03T22:56:23 COT">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@3e6104fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AbrirNavegador -->
        <test-method status="FAIL" signature="elegirArticulosAzarCarritoCompras()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="elegirArticulosAzarCarritoCompras" duration-ms="20" started-at="2021-10-03T22:56:23 COT" finished-at="2021-10-03T22:56:23 COT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Store] but found [508 Resource Limit Is Reached]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Store] but found [508 Resource Limit Is Reached]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.CasosCarrito.elegirArticulosAzarCarritoCompras(CasosCarrito.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elegirArticulosAzarCarritoCompras -->
        <test-method status="SKIP" signature="anadirProductosAlCarrito()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="anadirProductosAlCarrito" duration-ms="0" started-at="2021-10-03T22:56:23 COT" depends-on-methods="testcases.CasosCarrito.elegirArticulosAzarCarritoCompras" finished-at="2021-10-03T22:56:23 COT">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CasosCarrito.anadirProductosAlCarrito()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CasosCarrito.anadirProductosAlCarrito()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- anadirProductosAlCarrito -->
        <test-method status="SKIP" signature="verificarProductos()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="verificarProductos" duration-ms="0" started-at="2021-10-03T22:56:24 COT" depends-on-methods="testcases.CasosCarrito.anadirProductosAlCarrito" finished-at="2021-10-03T22:56:24 COT">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CasosCarrito.verificarProductos()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CasosCarrito.verificarProductos()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificarProductos -->
        <test-method status="SKIP" signature="verificarCheckOut()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="verificarCheckOut" duration-ms="0" started-at="2021-10-03T22:56:24 COT" depends-on-methods="testcases.CasosCarrito.verificarProductos" finished-at="2021-10-03T22:56:24 COT">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CasosCarrito.verificarCheckOut()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CasosCarrito.verificarCheckOut()[pri:0, instance:testcases.CasosCarrito@2bec854f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verificarCheckOut -->
        <test-method status="PASS" signature="cerrarNavegador()[pri:0, instance:testcases.CasosCarrito@2bec854f]" name="cerrarNavegador" is-config="true" duration-ms="457" started-at="2021-10-03T22:56:24 COT" finished-at="2021-10-03T22:56:24 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cerrarNavegador -->
      </class> <!-- testcases.CasosCarrito -->
    </test> <!-- Casos de Prueba Carrito de Compras -->
  </suite> <!-- Suite -->
</testng-results>
